version: '3.7'

services:

    cassandra:
      image: 'cassandra:3.11.3'
      restart: always
      volumes:
        - db-data:/var/lib/cassandra/data
      ports:
        - "9042:9042"

    api:
      build:
        context: workers
        dockerfile: services.docker
      restart: always
      ports:
        - '5002:5002'
      network_mode: "host"

    lang_detect:
      build:
        context: workers
        dockerfile: lang_detect.docker
      restart: always
      network_mode: "host"

    laser:
      build:
        context: workers
        dockerfile: laser.docker
      restart: always
      network_mode: "host"

volumes:
  redis:
  db-data:
    driver: local

networks:
  default:
    external:
      name: headstart_default