version: '2.3'

services:

    api:
      build:
        context: workers
        dockerfile: services.docker
      restart: always
      ports:
        - '5002:5002'
      network_mode: "host"

    lang_detect:
      build:
        context: workers
        dockerfile: lang_detect.docker
      restart: always
      network_mode: "host"

    nlp:
      build:
        context: workers
        dockerfile: nlp.docker
      restart: always
      network_mode: "host"

    # laser:
    #   build:
    #     context: workers
    #     dockerfile: laser.docker
    #   restart: always
    #   network_mode: "host"
    #   runtime: nvidia
    #   environment:
    #     - NVIDIA_VISIBLE_DEVICES=all
    #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    gusem:
      build:
        context: workers
        dockerfile: gusem.docker
      restart: always
      network_mode: "host"
      runtime: nvidia
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      volumes:
        - /home/chris/models:/models

volumes:
  redis:
  db-data:
    driver: local

networks:
  default:
    external:
      name: headstart_default