FROM python:3.6

MAINTAINER Chris Kittel "christopher.kittel@openknowledgemaps.org"

# set working directory
WORKDIR /app

COPY requirements_summarizer.txt requirements.txt
RUN pip install -r requirements.txt
RUN python -m nltk.downloader stopwords

COPY . .
