apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11
        env:
          - name: CASSANDRA_USER
            valueFrom:
              secretKeyRef:
                name: cassandra-credentials
                key: user
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: CASSANDRA-credentials
                key: password
        volumeMounts:
          - name: cassandra-volume-mount
            mountPath: /var/lib/cassandra/data
      volumes:
      - name: cassandra-volume-mount
        persistentVolumeClaim:
          claimName: cassandra-pvc
restartPolicy: Always
