apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
volumeName: cassandra-pv
