apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
path: "/data/cassandra-pv"
