FROM python:3.6

MAINTAINER Chris Kittel "web@christopherkittel.eu"

# set working directory
WORKDIR /workers

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
COPY ../../headstart-models/models/w2v_model_en .
COPY ../../headstart-models/models/w2v_model_en.vectors.npy .
