FROM python:3.6

MAINTAINER Chris Kittel "christopher.kittel@openknowledgemaps.org"

# set working directory
WORKDIR /workers

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY *.py ./
COPY models/w2v_model_en .
COPY models/w2v_model_en.vectors.npy .
